In [1]:
import numpy as np
arr=np.random.randn(2)
arr1=np.random.randn(5,5)
print(arr)
print(arr1)

[-1.42174837  0.97875693]
[[-0.71187929 -0.66924573  0.43149572 -1.23291313 -0.86535897]
 [-0.29310376  0.15407769 -0.8358243   0.80515346  0.91778654]
 [-0.09471007 -0.92657447  1.91992927  0.56775971  1.27842774]
 [ 0.16737853 -0.0465488   1.00279189 -0.58447728 -0.33091142]
 [-2.73666326 -1.40361013 -0.32839372  0.44430027 -0.56107393]]


In [2]:
arr=np.random.randint(2)
arr1=np.random.randint(5,5)
print(arr)
print(arr1)

ValueError: low >= high

In [3]:
arr=np.random.randint(2)
arr1=np.random.randint(1,100,10)
print(arr)
print(arr1)

0
[54 57 98  3 44 17 74 49  4 39]


In [4]:
arr=np.random.randint(1,100)
arr1=np.random.randint(1,100,10)
print(arr)
print(arr1) 

73
[49 32 60 57 55 91 30  2 34 52]


In [5]:
print(arr.itemsize)

AttributeError: 'int' object has no attribute 'itemsize'

In [6]:
arr=np.array([1,2,3,4,5])
print(arr.itemsize)

4


In [7]:
print(arr.itemsize)

4


In [8]:
x=np.array([" Riya"," Sankul"])
print(x.itemsize)

28


In [9]:
arr=np.array([1,2,3,4,5])
print(arr.max())

5


In [10]:
arr=np.array([1,2,3,4,5])
print(arr.max())
print(arr.argmax())
print(arr.min())
print(arr.argmin())

5
4
1
0


In [11]:
print(arr.shape)

(5,)


In [12]:
print(arr.reshape(1,25))

ValueError: cannot reshape array of size 5 into shape (1,25)

In [14]:
arr1=np.array([1,2,3])
arr2=np.array([[4],[5],[6]])
arr3=arr1+arr2
print(arr3)
print(arr3.shape)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
(3, 3)


In [18]:
b=np.arange(24)
c=b.reshape(2,4,3)
a=b.reshape(4,6)
print(a)
print(b)
print(c)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [26]:
arr_2d=np.array(([5,10,15],[20,25,30],[35,40,45]))
print(arr_2d)
print(arr_2d[1])
print(arr_2d[1][0])
print(arr_2d[1,0])
print("Silicing=",arr_2d[:2,1:])
print(arr_2d[2])

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[20 25 30]
20
20
Silicing= [[10 15]
 [25 30]]
[35 40 45]


In [23]:
arr=np.arange(1,11)
print(arr>4)
bool_arr=arr>4
arr[bool_arr]
print(arr)
print(arr[bool_arr])

[ 1  2  3  4  5  6  7  8  9 10]
[ 5  6  7  8  9 10]


In [24]:
print(arr[arr>2])

[ 3  4  5  6  7  8  9 10]


In [25]:
print(arr[arr<2])

[1]


In [27]:
arr=np.arange(1,11)
print(arr>4)
bool_arr=arr>4
arr[bool_arr]
print(arr)
print(arr[bool_arr])

[False False False False  True  True  True  True  True  True]
[ 1  2  3  4  5  6  7  8  9 10]
[ 5  6  7  8  9 10]


In [28]:
import pandas as ap

In [33]:
import pandas as pd
data=[10,20,30,40,50]
index=['A','B','C','D','E']
series=pd.Series( data,index=index)
print(series)
print(pd.__version__)

A    10
B    20
C    30
D    40
E    50
dtype: int64
1.4.3


In [38]:
import numpy as np
import pandas as pd
labels=['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={'a':10,'b':20,'c':30}
#using lists
print(pd.Series(data=my_list))
print(pd.Series(data=my_list,index=labels))
print(pd.Series(arr))
print(pd.Series(d))
print(pd.Series(d,labels))
data=np.array(['a','b','c','d'])
s=pd.Series(data,index=[100,101,102,103])
print(s)

0    10
1    20
2    30
dtype: int64
a    10
b    20
c    30
dtype: int64
0    10
1    20
2    30
dtype: int32
a    10
b    20
c    30
dtype: int64
a    10
b    20
c    30
dtype: int64
100    a
101    b
102    c
103    d
dtype: object


In [42]:
ser1=pd.Series([1,2,3,4],index=['USA','GERMANY','USSR','JAPAN'])
ser2=pd.Series([1,2,5,4],index=['USA','GERMANY','ITALY','JAPAN'])
print(ser1['USA'])
print(ser1+ser2)

1
GERMANY    8.0
ITALY      NaN
JAPAN      8.0
USA        2.0
USSR       NaN
dtype: float64


In [45]:
print(ser1.iloc[0])
print(ser1.loc['USA'])
print(ser1>20)

1
1
USA        False
GERMANY    False
USSR       False
JAPAN      False
dtype: bool


In [49]:
new_index=['a','b','c','d']
new_series=series.reindex(new_index)
print(new_series)

a   NaN
b   NaN
c   NaN
d   NaN
dtype: float64


In [50]:
import pandas as pd
data=[1,2,3,4,5]
labels=['First','Second','Third','Fourth','Fifth']
df=pd.DataFrame(data,labels)
print(df)

        0
First   1
Second  2
Third   3
Fourth  4
Fifth   5


In [52]:
data={'Name':['Jhon','Alice','Bob'],
     'Age':[25,30,35],'City':['New York','London','Paris']}
df=pd.DataFrame(data)
print(df)

    Name  Age      City
0   Jhon   25  New York
1  Alice   30    London
2    Bob   35     Paris


In [53]:
print(df['Name'])

0     Jhon
1    Alice
2      Bob
Name: Name, dtype: object


In [54]:
print(df['Age'])

0    25
1    30
2    35
Name: Age, dtype: int64


In [58]:
print(df[['Name','Age']])

    Name  Age
0   Jhon   25
1  Alice   30
2    Bob   35


In [69]:
#creating a new column
from numpy.random import randn
df=pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
df['new']=df['W']+df['Y']
(df)


W         X         Y         Z       new
A  0.960672 -1.362492 -0.881918  0.035027  0.078754
B  0.039561  0.881111 -0.023240  1.672797  0.016321
C -1.057075  0.440226 -0.459195 -1.209022 -1.516270
D -0.704022 -1.719786  0.051095 -0.577503 -0.652927
E -1.384259 -1.697912  1.276545  0.912201 -0.107714

In [68]:
df.drop('new',axis=1)

W         X         Y         Z
A  0.335004  0.249286  0.564544  2.069171
B  1.906928 -0.542916 -0.448430 -1.808642
C -0.107699  0.029901  0.607763 -1.078261
D  0.232188  1.142049 -0.662631 -0.487857
E -0.804471  0.084903 -0.557118 -0.390660

In [73]:
df

W         X         Y         Z
A  0.960672 -1.362492 -0.881918  0.035027
B  0.039561  0.881111 -0.023240  1.672797
C -1.057075  0.440226 -0.459195 -1.209022
D -0.704022 -1.719786  0.051095 -0.577503
E -1.384259 -1.697912  1.276545  0.912201

In [76]:
df.drop('C')

W         X         Y         Z
A  0.960672 -1.362492 -0.881918  0.035027
B  0.039561  0.881111 -0.023240  1.672797
D -0.704022 -1.719786  0.051095 -0.577503
E -1.384259 -1.697912  1.276545  0.912201

In [87]:
update_df=df.drop([df.index[1],df.index[2]])
update_df

W         X         Y         Z
A  0.960672 -1.362492 -0.881918  0.035027
D -0.704022 -1.719786  0.051095 -0.577503
E -1.384259 -1.697912  1.276545  0.912201

In [88]:
df.loc['A']

W    0.960672
X   -1.362492
Y   -0.881918
Z    0.035027
Name: A, dtype: float64

In [1]:
df.loc['A']


NameError: name 'df' is not defined