In [3]:
import numpy


In [4]:
import numpy as np


In [5]:
arr=np.array([1,2,3,4,5])

In [6]:
print(arr)

[1 2 3 4 5]


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
name=np.array(["Riya", "Sankul"])
print(name)

['Riya' 'Sankul']


In [9]:
print(type(name))

<class 'numpy.ndarray'>


In [10]:
print(name[1])

Sankul


array([1, 2, 3, 4])

In [12]:
my_list=["Riya",1,2,3]
np.array(my_list)

array(['Riya', '1', '2', '3'], dtype='<U11')

In [13]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a=np.array(42)
c=np.array([[1,2,3],[4,5,6]])

In [15]:
print(arr.ndim)

1


In [16]:
print(c.ndim)

NameError: name 'c' is not defined

In [17]:
c=np.array([[1,2,3],[4,5,6]])

In [18]:
print(c.ndim)


2


In [19]:
d=np.array([[[1,2,3],[4,5,6],[7,8,9],[4,5,6]]])

In [20]:
print(d.ndim)

3


In [21]:
print("Shape",d.shape)

Shape (1, 4, 3)


In [22]:
print("type",d.dtype)

type int32


In [23]:
print("type",array)

NameError: name 'array' is not defined

In [24]:
print("type",my_list)

type ['Riya', 1, 2, 3]


In [25]:
print("type",my_list.dtype)

AttributeError: 'list' object has no attribute 'dtype'

In [26]:
 arr_sum=c+d

ValueError: operands could not be broadcast together with shapes (2,3) (1,4,3) 

In [27]:
a=[[1,2,3],[4,5,6]],[[4,5,6],[1,2,3]]
print(a.ndim)

AttributeError: 'tuple' object has no attribute 'ndim'

In [28]:
a=np.array[[1,2,3],[4,5,6]],[[4,5,6],[1,2,3]]
print(a.ndim)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [29]:
arr1=np.array([[1,2,3],[4,5,6]],[[4,5,6],[1,2,3]])
print(arr1.ndim)

TypeError: Field elements must be 2- or 3-tuples, got '[4, 5, 6]'

In [30]:
arr1=np.array([[1,2,3],[4,5,6]],[[4,5,6],[1,2,3]])
print(arr1.ndim)

TypeError: Field elements must be 2- or 3-tuples, got '[4, 5, 6]'

In [31]:
print(arr1.shape)

NameError: name 'arr1' is not defined

In [32]:
arr1=np.array([[1,2,3],[4,5,6]],[[4,5,6],[1,2,3]])
print(arr1.ndim)
print(arr1.shape)
print(arr1.dtype)

TypeError: Field elements must be 2- or 3-tuples, got '[4, 5, 6]'

In [33]:
d=np.array([[[1,2,3],[4,5,6],[7,8,9],[4,5,6]]])
print("Element at index(1,2):",d[1,2])

IndexError: index 1 is out of bounds for axis 0 with size 1

In [34]:
d=np.array([[[1,2,3],[4,5,6],[7,8,9],[4,5,6]]])
print("Element at index(1,2):",d[1,])

IndexError: index 1 is out of bounds for axis 0 with size 1